rose-pine/neovim

lua/rose-pine/theme.lua, readme.md
Colors are set by default in todo-comments. 
Overriding these colors blocked default ["wide" highlight style](https://github.com/folke/todo-comments.nvim/blob/808a2e524b3720804716a99fd900986b9d727d4d/README.md#%EF%B8%8F-configuration) behavior:
```lua
highlight = {
keyword = "wide",  -- "fg", "bg", "wide" or empty. (wide is the same as bg, but will also highlight surrounding characters)
}
```
=> remove todo-comments config

lua/rose-pine/theme.lua
This MR improves the highlight of concealed text. Here's an example:
| Before | After |
| --- | --- |
| ![Screenshot_20210824_220536](https://user-images.githubusercontent.com/58810330/130682677-d1b5deed-075a-4a9f-934b-d700c9d5a9eb.png) | ![Screenshot_20210824_220450](https://user-images.githubusercontent.com/58810330/130682728-7aa4ec45-8e0d-4101-98e4-4baf5e01b0d1.png) |
=> Fix conceal highlight

lua/rose-pine/galaxyline/theme.lua, lua/rose-pine/util.lua, readme.md
Hey, first of all thanks for this very pleasant colorscheme, I use it sometimes haha
I would love to see rose-pine vibes on my galaxyline too when using it, that's why I added this, but you could be thinking "But galaxyline doesn't allow this" well I added this feature on my own fork. Hopefully it will be recognized after a while and my changes merged to upstream once glepnir appears again lol.
This is an screenshot of how it looks like on my galaxyline setup
Added the proper notes about the galaxyline theme in README, let me know if something should be changed.
Regards
=> feat: add galaxyline color theme, see notes in readme

lua/rose-pine/theme.lua
Since with the arrival of nvim 0.6.x changes were made to the names of the lsp hightlight groups, this PR presents a brief solution by correcting the erroneous names of the misspelled groups in the theme, and adding the nvim 0.5.x groups (making links to the already defined LSP colors).
An example of this is presented below:
- Before fixing the problem:
- After fixing the problem:
- New highlight groups defined in nvim 0.6.x
Conclusion: When the groups are not defined, the colors are blank because in the theme loading function there is a "hightligt clear", which makes them disappear completely and they are not redefined with the custom colors of the colorscheme because the group names defined in it do not match the lsp highlight groups.
=> Fix Lsp hightlight bug

lua/rose-pine/theme.lua
This feature require nvim_cmp `custom_menu` branch for now. 
See https://github.com/hrsh7th/nvim-cmp/pull/224 for more information.
=> feat: add highlight for nvim_cmp

lua/rose-pine/theme.lua, readme.md
This PR add an option for user to toggle the VertSplit style, just like [nord.vim](https://www.nordtheme.com/docs/ports/vim/configuration)
=> feat: add bold vertical split line option

lua/rose-pine/theme.lua
After upgrade, I notice that neogit highlight was broke. This PR fixed this issue. And I think the new contrast was too high in `moon` variant, so I made a little adjustment to them, too.
Contrast adjustment
Before
After
=> Fix neogit highlight and adjust the highlight contrast

lua/rose-pine/theme.lua
Improve support for the new experimental [Markdown TreeSitter plugin](https://github.com/MDeiml/tree-sitter-markdown) by matching the `TSTitle` style with the existing Markdown H1 heading. Turns
into this
=> fix: match Markdown headings for TS plugin

lua/rose-pine/theme.lua
This adds the lsp_signature highlight:
before:
after:
=> Add lsp_signature highlight

lua/rose-pine/theme.lua
VimwikiLink with underline style might be more intuitive.
=> vimwikilink add underline style

lua/rose-pine/theme.lua
PR #66 added highlights for nvim-notify. However, commit b425bbd84c08
removed them accidentally in a big refactor.
=> fix: Re-add nvim-notify highlights

lua/rose-pine/plugins/bufferline.lua, lua/rose-pine/plugins/toggleterm.lua, readme.md
=> add toggleterm highlights and initial bufferline highlights

lua/rose-pine/theme.lua
IMO, code lens text must be sufficiently distinguishable from the `Comment` but still fainter than `Normal` or `Text`
@mvllow what color do you think fit best ?
```text
LspCodeLens
|
+----+----+
|         |
^^^^^^^^^^^   ^^^^^
▶︎ Run Tests | Debug
^
|
+---> LspCodeLensSeparator
```
=> add `LspCodelensXXX` highlight group

lua/rose-pine/theme.lua
They recently merged https://github.com/neovim/neovim/pull/18081 which adds this group for the next release 0.8. I think it should probably not cause problems for people using earlier versions since there are highlights for random plugins people may not have.
I'm not a designer at all, so feel free to pick different colors, but I think these work well.
=> Add `CurSearch` highlight group

lua/rose-pine/theme.lua
close #82 
Give the `FloatTitle` a darker color, such as `muted`:
=> feat: improve contrast of the `FloatTitle`

lua/rose-pine/theme.lua, readme.md
Plugin: https://github.com/rcarriga/nvim-dap-ui
Original highlights: https://github.com/r/blob/master/lua/dapui/config/highlights.lua
closes #86
=> feat: Add nvim-dap-ui highlight groups

lua/rose-pine/theme.lua
Similar to `tokyonight.nvim`'s [implementation here](https://github.com/folke/tokyonight.nvim/blob/66bfc2e8f754869c7b651f3f47a2ee56ae557764/lua/tokyonight/theme.lua#L414). Let me know if you prefer different colors!
=> feat: Add neovim :checkhealth highlight groups

lua/rose-pine/theme.lua
The hlGroups `IndentBlanklineSpaceChar` and `IndentBlanklineSpaceCharBlankline` were missing from the theme, resulting in `listchars` showing up in a default blue colour.
=> fix: indent-blankline missing hlGroups

lua/rose-pine/theme.lua
Telescope float window had none background in case `disable_background = true` and `disable_float_background = false`, but it should not.
=> Fixed Telescope background 

lua/rose-pine/theme.lua
=> feat: add `NoiceCursor` highlight group

lua/rose-pine/theme.lua
Closes #139
Based on folke/tokyonight.nvim@827b05e, folke/tokyonight.nvim@c967c2c, folke/tokyonight.nvim@3ebc29d. Thank you, @folke!
=> Add support for lsp semantic token highlight groups (`@lsp.type(mod).*`)

lua/rose-pine/theme.lua
I think the rest of the colors for neo-tree seem fine (at least the ones I've ran across so far in the last couple of weeks since switching to it), but the title bar on the popups were a bit hard to read.
before:
after:
=> Add popup title bar color for NeoTree

lua/rose-pine/theme.lua
This PR adds highlights for [mini.indentscope](https://github.com/echasnovski/mini.indentscope). Of course feel free to change the actual colors.
=> Add highlights for mini.indentscope

lua/rose-pine/theme.lua
example using [LazyVim](https://www.lazyvim.org/)'s built-in UI that uses [goolord/alpha-nvim](https://github.com/goolord/alpha-nvim) under the hood:
=> feat: highlights for goolord/alpha-nvim

lua/rose-pine/config.lua, lua/rose-pine/theme.lua, readme.md
You now need to opt out of `respect_default_hightlight_groups` if you'd like highlight_group settings to be fully overwritten (even for options you didn't touch).
Previously, setting only one option for a highlight_group would reset the highlight group completely and only apply that option. This is really frustrating if all you want to do is update which options are, for example, italic or bold.
Default rose-pine highlight groups now live in a table that gets updated with the users config before being applied (hence the huge amount of lines updated in theme.lua).
=> highlight_groups now gives option to set new opts while respecting defaults.

lua/rose-pine/theme.lua
=> feat: color for flash

readme.md
Trying to make the description in the readme regarding options for highlighting better.
=> typo and grammar fixed, Bonus: clarifying the option effect

readme.md
I had to find this information within a Reddit Post, and I thought it was relevant that the documentation for the theme itself had this available
=> docs: add `lualine.nvim` theme guide

lua/lualine/themes/rose-pine.lua
`styles.transparency` set to true
Before -
After -
=> feat(transparency): remove lualine background

lua/rose-pine.lua, lua/rose-pine/config.lua, lua/rose-pine/utilities.lua, readme.md
This PR adds new treesitter groups, ref https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1900679583
_Feedback is welcome_
```diff
{
enable = {
+    legacy_highlights = true
},
groups = {
+    note = "pine",
+    todo = "rose",
}
}
```
We may take this opportunity to refactor a lil, breaking out treesitter and plugin highlights into separate files.
Ref #216, #218
=> feat: add new treesitter highlights

lua/rose-pine.lua
https://github.com/nvim-neotest/neotest/
:wave: I'm switching to the Neotest runner and instead of adding theme support to my own set up I figured I'd add it to the plugin directly. I matched the colors roughly to those used by default in the plugin. I'd appreciate any suggestions to make the color selections better align with the intentions of the theme and anything else needed to merge (e.g., do I need add to the `transparency_highlights` list as well?). Thanks!
=> feat: Add support for Neotest

lua/rose-pine.lua
Fix: when user defined highlights overrides existing highlights containing `link` attributes, them not applied due how `nvim_set_hl()` works: https://neovim.io/doc/user/api.html#nvim_set_hl()
=> fix: traverse existing highlight links when used with another attributes

lua/rose-pine.lua
Might fix #228 
This pr simply defines the treesitter highlight groups `@markup.heading.*.markdown` and `@markup.heading.*.marker.markdown` to make different levels of markdown headings distinguishable when treesitter is enabled on markdown files.
=> feat: make markdown headings distinguishable with treesitter

lua/rose-pine.lua
=> fix: use treesitter highlights for @lsp.type.variable

lua/rose-pine.lua
This commit prioritises semantic variables over treesitter—useful in cases such as Svelte strings with variables:
```svelte
<Card title="Welcome back, {username}" />
```
Previously `{username}` would have been highlighted as a string. Now, it is highlighted as a variable.
=> feat: prioritise semantic variable highlighting

lua/rose-pine/config.lua
See: https://riptutorial.com/lua/example/26503/emulating-ternary-operator-with--and---or--logical-operators-#undefined
=> fix(migrate): avoid ternary 'falls through' state

lua/rose-pine.lua
Adds [highlight groups](https://github.com/folke/tokyonight.nvim/blob/610179f7f12db3d08540b6cc61434db2eaecbcff/lua/tokyonight/theme.lua#L397) for [folke/trouble.nvim](https://github.com/folke/trouble.nvim). Trying to mimic the colors laid out in the first link to tokyonight theme, but it's a bit arbitrary. Let me know if you'd prefer some other colors.
=> feat: add highlight groups for folke/trouble.nvim

lua/rose-pine.lua
Adds highlights for [mini.statusline](https://github.com/echasnovski/mini.statusline). Let me know if other colors would would be preferable
=> feat: Add mini.statusline highlights

lua/rose-pine.lua
Problem: When switching the colorscheme from rose-pine to something else, the new colorshceme can be a bit off due to rose-pine's autocmd.
Solution: Clear the autocmd.
Ideally, it should also reset winhighlight for all windows it touched, but that requires a bit more work.
=> fix: clear autocmd when loading other colorscheme

lua/rose-pine.lua
This pull requests add support for the [nvim-treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context) plugin by adding some default highlighting.
The result will look like this:
=> Add default highlights for nvim-treesitter-context

lua/rose-pine.lua
After updating to ea0d8dbc8e126d38cbc12c8ed0ee6deec4e95dbf I started seeing this error:
```
  Error  10:00:18 PM notify.error lazy.nvim Failed to run `config` for rose-pine
vim/_editor.lua:0: /home/dgreene/.config/nvim/init.lua..nvim_exec2() called at /home/dgreene/.config/nvim/init.lua:0../home/dgreene/.local/share/nvim/lazy/rose-pine/colors/rose-pine-moon.lua: Vim(colorscheme):E5113: Error while calling lua chunk: ...reene/.local/share/nvim/lazy/rose-pine/lua/rose-pine.lua:874: Invalid highlight color: 'overlay'
stack traceback:
[C]: at 0x55ddd3901ae5
...reene/.local/share/nvim/lazy/rose-pine/lua/rose-pine.lua:874: in function 'set_highlights'
...reene/.local/share/nvim/lazy/rose-pine/lua/rose-pine.lua:920: in function 'colorscheme' …
```
=> Fix issue where palette value wasn't being referenced correctly

lua/rose-pine.lua
The transparency options don't currently set the TabLine. Here is a before & after:
=> For transparency, remove BG for buffers and gray out the text

lua/rose-pine.lua
The `@float`capture group is now linked to `Number`. Query files that use this capture group are now highlighted corrected when using treesitter.
__Before__:
__After__:
=> Added ["@float"] to default_highlights (#272)

lua/rose-pine.lua
This PR adds explicit support for all  highlight groups used in 'mini.nvim' (and even some upcoming ones).
The existing ones are mostly kept as is (except `MiniIndentscopeSymbolOff` which is changed to be more visible, as it is intended to draw attention that indent is off).
=> feat: add explicit full 'mini.nvim' support

lua/rose-pine.lua
=> Fix: link `@lsp.type.comment.c` and `@lsp.type.comment.cpp` to `@comment`

lua/rose-pine.lua
Add support for [rainbow-delimiters.nvim](https://github.com/HiPhish/rainbow-delimiters.nvim) for colorful matching brackets, parenthesis, braces.
Example of plugin in action:
=> feat: add support for rainbow-delimiters.nvim

lua/rose-pine.lua
The highlight for `NeotestIndent` was missing... and made the tree look very out of place IMO. 
This tree whether expanded or collapsed always shows `NeotestExpandMarker` which was already set to `highlight_med`, so having 2 different colors makes things look very off.
Before and after:
=> fix: add missing highlight for `NeotestIndent`

lua/rose-pine.lua
Fixes the broken transparency for treesitter-context background. These highlights were not added to `transparency_highlights` in the initial commit when support was first added.
=> fix: broken transparency for treesitter-context

lua/rose-pine.lua
Found the offending highlight groups and corrected them. 😄 
Closes #283 
Result:
=> fix: fzf-lua invisible selection

lua/rose-pine.lua
Add support for [grug-far.nvim](https://github.com/MagicDuck/grug-far.nvim) - a new super simple find and replace plugin powered by ripgrep.
=> feat: add support for grug-far.nvim

lua/rose-pine.lua
Reference to change: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/aeb5cec617c3bd5738ab82ba2c3f9ccdc27656c2
=> chore: markdown.nvim renamed to render-markdown.nvim

lua/rose-pine/config.lua, lua/rose-pine/palette.lua, readme.md
Should partially implement #276 (if i read it correctly).
Allows users to override the default color palette without `before_highlight` using a new config option
`palette`.  This does not allow the addition of new variants, only the modification of existing ones, but this implementation could easily be extended to support the addition of new palette variants.
Proposed functionality:
``` lua
pallet = {
-- override (or append) default color palette of specified variants
-- moon = {
--     base = '#18191a',
--     overlay = '#363738',
-- },
},
```
Edit: removed all option
=> feat: palette overrides

lua/rose-pine.lua, lua/rose-pine/plugins/obsidian.lua
- Added highlight support for epwalsh/obsidian.nvim for bullets, done checkboxes, reference links
fixes #322 
Below is a screenshot of a working example of some of the changes
=> feat: add highlight support for epwalsh/obsidian.nvim

lua/rose-pine.lua
Added highlight support for folke/snacks.nvim indent module.
- Supports scope, blank, chunks and indent highlights
- Using same colors as lukas-reineke/indent-blankline.nvim
Below is a screenshot using my fork with the snacks indent plugin enabled
=> feat: add snacks indent highlights

lua/rose-pine.lua
This uses the same color for match highlight as telescope
Before 
After
=> More obvious match highlight in snacks.picker

lua/rose-pine.lua
The `SignAdd`, `SignChange`, and `SignDelete` are never referenced by any other highlight definitions than the previous `GitSigns` ones before this change.
The isolated definitions are only left for backward compatibility.
This change would help [ex-colors.nvim](https://github.com/aileot/ex-colors.nvim) applied straightforwardly to rose-pine. (sorry for this shameless suggestion.)
=> refactor(gitsigns): avoid redundant links

lua/rose-pine.lua
Add support for the [vim-sneak](https://github.com/justinmk/vim-sneak) plugin. The highlight groups are detailed [here](https://github.com/justinmk/vim-sneak/blob/18b1faf020e6a66c1ce09b3ff5e6b6feb182973b/doc/sneak.txt#L349).
This is a preview of how the different highlight groups look like. I decided to base the coloring on the current [flash.nvim](https://github.com/rose-pine/neovim/blob/20c7940da844aa4f162a64e552ae3c7e9fdc3b93/lua/rose-pine.lua#L529) for the labels and matches, and [leap.nvim](https://github.com/rose-pine/neovim/blob/20c7940da844aa4f162a64e552ae3c7e9fdc3b93/lua/rose-pine.lua#L653) for the scope.
=> feat: add support for vim-sneak

lua/rose-pine.lua
DapUIType uses purple fg atm, which can be changed to purple for consistent soho vibes. Let me know if it was an intentional choice not to override `DapUIType`:
https://github.com/rcarriga/nvim-dap-ui/blob/bc81f8d3440aede116f821114547a476b082b319/lua/dapui/config/highlights.lua#L20
=> Extends DapUIType foreground color to iris

lua/rose-pine.lua
The default `BlinkCmpDoc` highlight is linked to `NormalFloat`, which is a sensible default. However, due to overriding the default link with only `fg` provided, the `bg` is cleared and the documentation popup is indistinguishable from regular text.
This change is technically a no-op in terms of intended palette, because `NormalFloat` should already use `palette.text`, and only fixes the cleared `bg` bug.
Before:
After:
=> fix(blink.cmp): remove dedicated BlinkCmpDoc highlight

lua/rose-pine.lua
Although the default of `NormalFloat` is a sensible value for the documentation float, it has the same highlight as `Pmenu`, which means that on narrow displays where the documentation window is shown below the completion menu, it is not always clear where the completion items end and where the documentation begins.
Setting the highlight to `palette.overlay` (compared to the default of `palette.surface`) adds a visual cue to separate the completion menu from the documentation window, without straying too much from the defaults.
Before:
After:
=> fix(blink.cmp): set BlinkCmpDoc background to palette.overlay

lua/rose-pine.lua
This pull request adds the `QuickFixLine` highlight group (which seems to have been previously included as "`QuickFixLink`" and commented out). The built-in color for this group is `NvimLightCyan`, so `foam` seems to be a good choice.
=> feat: add `QuickFixLine`

lua/rose-pine.lua
This pull request adds the `ModesFormat` highlight group recently added in [modes.nvim](https://github.com/mvllow/modes.nvim).
=> feat: add `ModesFormat`

lua/rose-pine.lua
This small change fixes an issue where `blend` property was being cleared from highlight, causing transparency to stop working. It seems like that line was added by mistake.
Before: 
After:
=> fix: do not clear `blend` prop from highlight

lua/rose-pine.lua
- Add highlight support for `AvantePromptInput` and `AvantePromptInputBorder` in avante.nvim
- Follows the established styling pattern used by CMP and Blink completion menu inputs
- Uses `groups.panel` background with `palette.text` foreground for consistency
The avante.nvim plugin defines prompt input highlight groups that were previously unstyled in the rose-pine theme. This PR adds proper styling that matches the existing completion menu patterns:
- `AvantePromptInput`: Panel background with readable text foreground
- `AvantePromptInputBorder`: Standard border styling using `groups.border`
- I tested locally
| Before | After |
|--------|--------|
| <img width="357" height="87" alt="image" src="https://github.com/user-attachments/assets/a2c452b9-4dc6-4edf-9a0a-840446c938eb" /> | <img …
=> feat: add AvantePromptInput highlight support
