- lua/lualine/themes/rose-pine.lua
Hi, thanks for the awesome colorscheme! 
This PR adds support for [lualine](https://github.com/hoob3rt/lualine.nvim).
> Add lualine theme

- lua/rose-pine/theme.lua
Hi, I was having problems with highlighting using todo-comments [#59](https://github.com/folke/todo-comments.nvim/issues/59)
So I took a look at the color section for the todo-comments and fixed it.
before
after
> fixed background color

- readme.md
> add lualine setup and supported plugins

- lua/rose-pine/theme.lua
- readme.md
This pr aims to add highlight for this useful plugin https://github.com/lukas-reineke/indent-blankline.nvim
> add(highlight): indent-blankline.nvim

- lua/rose-pine/theme.lua
- readme.md
> feat: add support for neogit

- lua/rose-pine/theme.lua
This should close #36.
For information sake, the colors and the arrangement is very personal,
and can be subject to changes.
Feel free to complete the list of supported CmpItemKind from there: https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/types/lsp.lua#L108
> feat: Add more highlights to nvim-cmp

- lua/rose-pine/theme.lua
- readme.md
This PR follows https://github.com/rose-pine/neovim/pull/59
> feat: add support for pounce.nvim

- lua/rose-pine/theme.lua
My take on vim-notify highlights 💪🏻 🤩 
New highlights:
> feat: Add nvim-notify highlights

- lua/rose-pine/init.lua
- readme.md
> add highlight groups

- lua/rose-pine/theme.lua
Added hlGroups for [dashboard](github.com/glepnir/dashboard-nvim)
> feat:  add hlGroups for dashboard-nvim

- readme.md
> docs: remove tag option from Packer snippet

- lua/rose-pine/plugins/markid.lua
This is reference contribution to #97 .
Hope you find it suitable, else feel free to tell me what to modify.
> feat: Add support to markid (#97)

- colors/rose-pine.lua
- colors/rose-pine.vim
Yes, we can use Lua files pretty much everywhere :)
> chore: rename colors/rose-pine.{vim => lua}

- lua/rose-pine/config.lua
- lua/rose-pine/palette.lua
- lua/rose-pine/theme.lua
- readme.md
Adds `groups.backbround_nc` and `groups.panel_nc`.
Closes #128
> feat: add `background_nc` and `panel_nc` groups

- lua/rose-pine/theme.lua
Added highlight groups for [ggandor/leap.nvim](https://github.com/ggandor/leap.nvim)
> feat: added leap highlight groups

- lua/rose-pine/theme.lua
> feat: add lsp injected highlights

- lua/rose-pine/theme.lua
> fix(indent-blankline): fix italic indent lines

- lua/rose-pine/theme.lua
https://github.com/phaazon/hop.nvim
> feat: colors for hop

- lua/rose-pine/theme.lua
In a attempt make it more like telescope colors.
> Add support for `fzf-lua`

- lua/rose-pine.lua
> feat: re-add inherit option for custom highlight groups

- lua/rose-pine/palette.lua
> fix: none palette value

- lua/rose-pine.lua
> fix: transparency not affecting Normal background

- lua/rose-pine.lua
Use new (shortend) syntax for indent-blankline. (ibl)
> style(ibl): update highlights for indent-blanklines

- lua/rose-pine.lua
> fix: unlink TabLine from StatusLine

- lua/rose-pine.lua
> chore: update variable highlights

- lua/rose-pine.lua
> feat: highlight lsp variable constant

- lua/rose-pine.lua
Fixes Issue #256. Initial testing shows that produces a favorable change but is difficult for me to know if it bothers any other languages other than the 4 I looked at (Python, R, SQL, Lua).
> fix(python): import semantic_tokens from basedpyright

- lua/rose-pine.lua
[modes.nvim](https://github.com/mvllow/modes.nvim) is about to incorporate replace mode.
> feat: support upcoming modes.nvim update

- lua/rose-pine.lua
> feat: improve diff text

- lua/rose-pine.lua
> feat: highlight neotree tabs

- lua/lualine/themes/rose-pine.lua
> fix(transparency): lualine separator

- lua/rose-pine.lua
Signed-off-by: Aaron Pham <contact@aarnphm.xyz>
> feat(plugins): add support for avante.nvim

- lua/rose-pine.lua
> feat(transparency): support trouble.nvim

- lua/rose-pine.lua
Though I could not reproduce the issue, but this change would probably  fix https://github.com/rose-pine/neovim/issues/321.
> fix: set `background=light` if variant is "dawn"
